export const INITIAL_CLIENTE = {
  id: "",
  nome: "",
  cpfCnpj: "",
  endereco: "",
  numero: "",
  complemento: "",
  bairro: "",
  cidade: "",
  uf: "",
  cep: "",
  telefone: "",
  celular: "",
  email: "",
  dataNascimento: "",
  observacao: "",
}
